=== Eduin321/Examen/Examen/Reglas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="bib">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" minOccurs="1" type="xs:string" />
                            <xs:element ref="autor" minOccurs="1" maxOccurs="unbounded" />
                            <xs:element name="editorial" minOccurs="1" type="xs:string" />
                            <xs:element name="precio" minOccurs="1" type="xs:decimal" />
                            <xs:element name="codigoPais" minOccurs="1" default="ESP">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="ESP" />
                                        <xs:enumeration value="ITA" />
                                        <xs:enumeration value="FRA" />
                                        <xs:enumeration value="ALE" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="anyo">
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="nombre" type="xs:string" />
            <xs:attribute name="centro" type="xs:string" />
            <xs:attribute name="portada" type="xs:string" />
        </xs:complexType>
    </xs:element>

    <xs:element name="autor">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="apellido" minOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[a-z]" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="nombre" minOccurs="1" type="xs:string" />
                <xs:element name="cedula" minOccurs="1" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="foto" type="xs:string" />
            <xs:attribute name="id" type="xs:string" />
        </xs:complexType>
    </xs:element>
    
    
    <xs:complexType name="infoautor">
        <xs:sequence>
            <xs:element name="ciudad" type="xs:string"/>
            <xs:element name="pais" type="xs:string"/>
            <xs:element name="telefono" type="xs:string"/>
            <xs:element name="correo" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>


<complexType>

</complexType>

=== Eduin321/Examen/Examen/Ejercicio1.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="XSLT/ejercicio.xsl" ?>
<!DOCTYPE ventas SYSTEM "Rreglas.dtd">
<bib xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Reglas.xsd">

    <libro anyo="1994">
            <titulo>TCP/IP Illustrated</titulo>
            <autor id="mm" foto="https://crearmiempresa.es/wp-content/uploads/2015/07/frases-de-steve-jobs.jpg">
                <apellido>stevensG</apellido>
                <nombre>W.</nombre>
                <cedula></cedula>
            </autor>
            <editorial>Addison-Wesley</editorial>
            <precio>65.95</precio>
            <codigoPais>ESP</codigoPais>
        </libro>
        <libro anyo="1992">
            <titulo>Advanced Programming for Unix environment</titulo>
            <autor id="pp">
                <apellido>stevens</apellido>
                <nombre>W.</nombre>
                <cedula></cedula>
            </autor>
            <editorial>Addison-Wesley</editorial>
            <precio>65.95</precio>
        </libro>
        <libro anyo="2000">
            <titulo>Data on the Web</titulo>
            <autor id="yy">

                <apellido>abiteboul</apellido>
                <nombre>Serge</nombre>
                <cedula></cedula>
            </autor>
            <autor id="k">
                <apellido>buneman</apellido>
                <nombre>Peter</nombre>
            </autor>
            <autor>
                <apellido>suciua</apellido>
                <nombre>Dan</nombre>
            </autor>
            <editorial>Morgan Kaufmann editorials</editorial>
            <precio>39.95</precio>
        </libro>
        <libro anyo="1999">
            <titulo> Economics of Technology for Digital TV</titulo>
            <autor id="qq">
                <apellido>gerbarg</apellido>
                <nombre>Darcy</nombre>
                <cedula></cedula>

            </autor>
            <editorial>Kluwer Academic editorials</editorial>
            <precio>129.95</precio>
        </libro>
</bib>
